[versions]
accompanistWebview = "0.30.1"
agp = "8.9.3"
coilCompose = "2.4.0"
firebaseBom = "34.6.0"
kotlin = "2.1.10"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.3"
activityCompose = "1.11.0"
composeBom = "2025.09.01"

navVersion = "2.9.4"
serialization = "1.7.3"
ktor = "2.3.12"
koin = "4.0.0-RC1"
koin-annotation = "1.4.0-RC3"
materialIcon = "1.7.8"
ksp = "2.1.0-1.0.29"


dataStore = "1.1.4"
atomicfu = "0.24.0"
googleGmsGoogleServices = "4.4.4"
credentials = "1.5.0"
credentialsPlayServicesAuth = "1.5.0"
googleid = "1.1.1"

[libraries]
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanistWebview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

#Navigation
navigation-compose = {module = "androidx.navigation:navigation-compose", version.ref = "navVersion"}
navigation-serialization-json = {module = "org.jetbrains.kotlinx:kotlinx-serialization-json",version.ref = "serialization"}
#Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
#Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-coroutines = { module = "io.insert-koin:koin-core-coroutines", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-annotation = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotation" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotation" }

#DataStore
dataStorePreferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" } #Provides Thread Safe Singleton
#Material Icon
material-icon = { module = "androidx.compose.material:material-icons-extended", version.ref ="materialIcon"}

#SystemUIController

play-services-auth = { module = "com.google.android.gms:play-services-auth" }
androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
navigation-serialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

[bundles]

navigation = [
    "navigation-compose",
    "navigation-serialization-json"
]

ktor = [
    "ktor-client-core",
    "ktor-client-okhttp",
    "ktor-client-content-negotiation",
    "ktor-client-logging",
    "ktor-serialization-kotlinx-json"
]

koin = [
    "koin-core",
    "koin-android",
    "koin-compose",
    "koin-compose-viewmodel",
    "koin-annotation",
    "koin-ksp-compiler",
    "koin-coroutines"
]

dataStore = [
    "dataStorePreferences",
    "atomicfu"
]

